### ISSUE TITLE
Fix problem with 'guest_quote_with_addresses.php' fixture

### ISSUE THREAD

**Issue by naydav** [magento/graphql-ce#534]
```
PHP Fatal error:  Uncaught Exception: Exception occurred when running the "\/var\/www\/html\/dev\/tests\/integration\/testsuite\/Magento\/Sales\/_files\/guest_quote_with_addresses.php" fixture: 
14:31:12 [WebAPI GRAPHQL-Tests-EE] URL key for specified store already exists. in /var/www/html/dev/tests/api-functional/framework/Magento/TestFramework/Annotation/ApiDataFixture.php:114
14:31:12 [WebAPI GRAPHQL-Tests-EE] Stack trace:
14:31:12 [WebAPI GRAPHQL-Tests-EE] #0 /var/www/html/dev/tests/api-functional/framework/Magento/TestFramework/Annotation/ApiDataFixture.php(137): Magento\TestFramework\Annotation\ApiDataFixture->_applyOneFixture('/var/www/html/d...')
14:31:12 [WebAPI GRAPHQL-Tests-EE] #1 /var/www/html/dev/tests/api-functional/framework/Magento/TestFramework/Annotation/ApiDataFixture.php(54): Magento\TestFramework\Annotation\ApiDataFixture->_applyFixtures(Array)
14:31:12 [WebAPI GRAPHQL-Tests-EE] #2 [internal function]: Magento\TestFramework\Annotation\ApiDataFixture->startTest(Object(Magento\GraphQl\Quote\Guest\GetAvailableShippingMethodsTest))
14:31:12 [WebAPI GRAPHQL-Tests-EE] #3 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/EventManager.php(49): call_user_func_array(Array, Array)
14:31:12 [WebAPI GRAPHQL-Tests-EE] #4 /var/www/html/dev/tes in /var/www/html/dev/tests/api-functional/framework/Magento/TestFramework/Annotation/ApiDataFixture.php on line 114
```

**Comment by atwixfirster** [comment]
Probably fix is a rollback for `Magento/Checkout/_files/simple_product.php` fixture. I faced `URL key for specified store already exists` error in https://github.com/magento/graphql-ce/pull/472. Also I've added a missed rollback there.

Thank you!

**Comment by naydav** [comment]
Fixed
https://github.com/magento/graphql-ce/pull/543
https://github.com/magento/graphql-ce/pull/472
